# Reference: https://docs.openshift.com/container-platform/4.11/networking/metallb/metallb-operator-install.html
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: metallb-operator
  namespace: metallb-system
---
# Confirm
# $ oc get operatorgroup -n metallb-system
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: metallb-system
spec:
  channel: stable
  name: metallb-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
---
# Optional
# $ oc label ns metallb-system "openshift.io/cluster-monitoring=true"

# Confirm install plan
# $ oc get installplan -n metallb-system

# Verify it is installed
# oc get clusterserviceversion -n metallb-system -o custom-columns=Name:.metadata.name,Phase:.status.phase

# Once operator is installed, create instance:
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system

# Verify deployment:
# $ oc get deployment -n metallb-system controller

# Verify speaker is running:
# $ oc get daemonset -n metallb-system speaker
---