# Reference: https://docs.openshift.com/container-platform/4.11/logging/cluster-logging-external.html#logging-forward-splunk_cluster-logging-external
# First HEC Token must be created:
# $ oc -n openshift-logging create secret generic vector-splunk-secret --from-literal hecToken=<HEC_Token>
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogForwarder"
metadata:
  name: "instance" 
  namespace: "openshift-logging" 
spec:
  outputs:
    - name: splunk-receiver 
      secret:
        name: vector-splunk-secret 
      type: splunk 
      url: <http://your.splunk.hec.url:8088> 
  pipelines: 
    - inputRefs:
        - application
        - infrastructure
      name: 
      outputRefs:
        - splunk-receiver 